name: Pull Request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: write-all
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Label PR size
        uses: flowdify/add-size-label-to-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request--size-small: 50
          pull-request--size-medium: 200
          pull-request--size-large: 1000

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'maven'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            maven-

      - name: Unit tests
        id: unit-tests
        run: mvn -B clean jacoco:prepare-agent verify jacoco:report

      - name: Notify JaCoCo Scan fail
        if: steps.unit-tests.outcome != 'success'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: REQUEST_CHANGES
          body: 'JaCoCo Scan is failed'

      - name: Notify JaCoCo scan success
        if: steps.unit-tests.outcome == 'success'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: COMMENT
          body: 'JaCoCo Scan is passed'

      - name: Approve Pull Request
        if: steps.unit-tests.outcome == 'success'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE

      - name: Terminate pipeline
        if: steps.unit-tests.outcome != 'success'
        run: exit 1