name: Release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          persist-credentials: true

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Give Maven Wrapper permission to run
        run: chmod +x mvnw

      - name: Install semantic-release plugins
        run: npm install @conveyal/maven-semantic-release -D

      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npx semantic-release --prepare @conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --skip-maven-deploy